#!/usr/bin/env bash
# ci-healer.sh — Run Playwright Healer Agent on failing E2E tests
# Usage: ./scripts/ci-healer.sh [--create-pr]
#
# 1. Runs E2E tests and captures failures
# 2. If failures exist, invokes the Healer Agent via Claude CLI
# 3. If --create-pr, creates a PR with the fixes
#
# Requires: @playwright/test, claude CLI, git
# Cost: ~27K tokens per failing test (CLI mode)

set -euo pipefail

CREATE_PR=false
if [ "${1:-}" = "--create-pr" ]; then
  CREATE_PR=true
fi

REPORT_DIR="playwright-report"
RESULTS_FILE="test-results.json"
HEAL_BRANCH="fix/e2e-heal-$(date +%Y%m%d-%H%M%S)"

echo "=== Playwright Healer CI ==="
echo ""

# 1. Run E2E tests
echo "Running E2E tests..."
npx playwright test --reporter=json 2>/dev/null > "${RESULTS_FILE}" || true

# 2. Check for failures
FAILED_COUNT=$(python3 -c "
import json, sys
try:
    with open('${RESULTS_FILE}') as f:
        data = json.load(f)
    suites = data.get('suites', [])
    failed = 0
    for suite in suites:
        for spec in suite.get('specs', []):
            for test in spec.get('tests', []):
                if test.get('status') == 'unexpected':
                    failed += 1
    print(failed)
except:
    print(0)
" 2>/dev/null || echo 0)

if [ "${FAILED_COUNT}" -eq 0 ]; then
  echo "✅ All E2E tests passed. No healing needed."
  rm -f "${RESULTS_FILE}"
  exit 0
fi

echo "❌ ${FAILED_COUNT} test(s) failed. Launching Healer Agent..."
echo ""

# 3. Create a branch for fixes
if [ "${CREATE_PR}" = true ]; then
  git checkout -b "${HEAL_BRANCH}" 2>/dev/null || true
fi

# 4. Run the Healer Agent via Claude CLI (uses CLI mode for cost efficiency)
claude -p "Use the healer agent to fix the ${FAILED_COUNT} failing E2E tests. \
Analyze the test results in ${RESULTS_FILE} and the playwright-report/. \
Only fix selector-related or timing issues. \
If a test failure indicates a real application bug, SKIP the test with a comment explaining the bug — do NOT mask it. \
After fixing, re-run the tests to verify." 2>&1 || {
  echo "⚠️ Healer Agent failed or timed out."
  echo "Manual investigation needed."
  exit 1
}

# 5. Check if any files were modified
MODIFIED=$(git diff --name-only 2>/dev/null || true)
if [ -z "${MODIFIED}" ]; then
  echo "Healer made no changes. Failures may be real bugs."
  rm -f "${RESULTS_FILE}"
  exit 1
fi

echo ""
echo "Healer modified:"
echo "${MODIFIED}" | sed 's/^/  - /'

# 6. Create PR if requested
if [ "${CREATE_PR}" = true ]; then
  git add -A
  git commit -m "fix(e2e): auto-heal failing tests

Automated fix by Playwright Healer Agent.
${FAILED_COUNT} test(s) were analyzed.

⚠️ Review required — verify these changes are correct.

Co-Authored-By: Playwright Healer Agent <noreply@playwright.dev>"

  git push -u origin "${HEAL_BRANCH}" 2>/dev/null || {
    echo "⚠️ Could not push branch. Create PR manually."
    exit 0
  }

  gh pr create \
    --title "fix(e2e): auto-heal ${FAILED_COUNT} failing test(s)" \
    --body "$(cat <<EOF
## Automated E2E Test Healing

The Playwright Healer Agent analyzed and fixed **${FAILED_COUNT}** failing E2E test(s).

### Modified files
$(echo "${MODIFIED}" | sed 's/^/- /')

### ⚠️ Review checklist
- [ ] Fixes are correct (not masking real bugs)
- [ ] Skipped tests have proper bug comments
- [ ] No business logic changes made

🤖 Generated by Playwright Healer Agent
EOF
)" \
    --label "automated,e2e" 2>/dev/null || echo "PR creation failed. Push succeeded — create PR manually."

  echo ""
  echo "✅ PR created on branch ${HEAL_BRANCH}"
else
  echo ""
  echo "Changes are local. Use --create-pr to auto-create a PR."
fi

# Cleanup
rm -f "${RESULTS_FILE}"
